# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 1
updates:
  # Enable version updates for npm
  - package-ecosystem: "php:composer"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check composer on a daily basis
    schedule:
      interval: "daily"
