name: Dependabot Merge

on:
  workflow_run:
    workflows: [ "Tests" ]
    types: [ "completed" ]

jobs:
  approve-and-merge:
    name: Approve and Merge
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request'}} &&
      ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ukcp-api-dependabot-auto-merge
      cancel-in-progress: true
    steps:
      - name: Download Pull Request Number
        uses: actions/download-artifact@v2
        with:
          name: pr-number
          path: ~/pr-number

      - name: Set Pull Request Number
        run: |
          NUM=$(cat ~/pr-number)
          echo "PR_NUMBER=$NUM" >> $GITHUB_ENV

      - name: Merge Dependabot
        uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          pr-number: ${{ env.PR_NUMBER }}
